server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/hotel_booking?createDatabaseIfNotExist=true
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    password: iiei grrs rafg agpv
    protocol: smtp
    username: nguyenvietvan223@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    test-connection: false

auth:
  token:
    jwtExpirationTime: 86400000 #1 hour in milliseconds
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
