server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/hotel_booking?createDatabaseIfNotExist=true
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

auth:
  token:
    jwtExpirationTime: 3600000 #1 hour in milliseconds
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
